# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from protos import examgen_pb2 as protos_dot_examgen__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in protos/examgen_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ExamAIServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.IndexLecture = channel.unary_unary(
                '/ExamAIService/IndexLecture',
                request_serializer=protos_dot_examgen__pb2.IndexLectureRequest.SerializeToString,
                response_deserializer=protos_dot_examgen__pb2.IndexLectureResponse.FromString,
                _registered_method=True)
        self.GenerateExam = channel.unary_unary(
                '/ExamAIService/GenerateExam',
                request_serializer=protos_dot_examgen__pb2.GenerateQuestionsRequest.SerializeToString,
                response_deserializer=protos_dot_examgen__pb2.GenerateQuestionsResponse.FromString,
                _registered_method=True)
        self.GradeAnswer = channel.unary_unary(
                '/ExamAIService/GradeAnswer',
                request_serializer=protos_dot_examgen__pb2.GradeAnswerRequest.SerializeToString,
                response_deserializer=protos_dot_examgen__pb2.GradeAnswerResponse.FromString,
                _registered_method=True)


class ExamAIServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def IndexLecture(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateExam(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GradeAnswer(self, request, context):
        """rpc GradeImageAnswer (GradeImageAnswerRequest) returns (GradeAnswerResponse);
        rpc ExplainConcept (ExplainConceptRequest) returns (ExplainConceptResponse);
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ExamAIServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'IndexLecture': grpc.unary_unary_rpc_method_handler(
                    servicer.IndexLecture,
                    request_deserializer=protos_dot_examgen__pb2.IndexLectureRequest.FromString,
                    response_serializer=protos_dot_examgen__pb2.IndexLectureResponse.SerializeToString,
            ),
            'GenerateExam': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateExam,
                    request_deserializer=protos_dot_examgen__pb2.GenerateQuestionsRequest.FromString,
                    response_serializer=protos_dot_examgen__pb2.GenerateQuestionsResponse.SerializeToString,
            ),
            'GradeAnswer': grpc.unary_unary_rpc_method_handler(
                    servicer.GradeAnswer,
                    request_deserializer=protos_dot_examgen__pb2.GradeAnswerRequest.FromString,
                    response_serializer=protos_dot_examgen__pb2.GradeAnswerResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ExamAIService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ExamAIService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ExamAIService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def IndexLecture(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ExamAIService/IndexLecture',
            protos_dot_examgen__pb2.IndexLectureRequest.SerializeToString,
            protos_dot_examgen__pb2.IndexLectureResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateExam(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ExamAIService/GenerateExam',
            protos_dot_examgen__pb2.GenerateQuestionsRequest.SerializeToString,
            protos_dot_examgen__pb2.GenerateQuestionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GradeAnswer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ExamAIService/GradeAnswer',
            protos_dot_examgen__pb2.GradeAnswerRequest.SerializeToString,
            protos_dot_examgen__pb2.GradeAnswerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
