# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/examgen.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'protos/examgen.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14protos/examgen.proto\"^\n\x13IndexLectureRequest\x12\x12\n\nlecture_id\x18\x01 \x01(\t\x12\x11\n\tcourse_id\x18\x02 \x01(\t\x12\x0f\n\x07user_id\x18\x03 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x04 \x01(\t\"V\n\x14IndexLectureResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x15\n\rerror_message\x18\x02 \x01(\t\x12\x16\n\x0e\x63hunks_indexed\x18\x03 \x01(\x05\"N\n\x0eLectureContent\x12\x12\n\nlecture_id\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\x12\x17\n\x0fquestions_count\x18\x03 \x01(\x05\"A\n\x13\x44ifficultyBreakdown\x12\x0c\n\x04\x65\x61sy\x18\x01 \x01(\x05\x12\x0e\n\x06medium\x18\x02 \x01(\x05\x12\x0c\n\x04hard\x18\x03 \x01(\x05\"?\n\rTypeBreakdown\x12\x0b\n\x03mcq\x18\x01 \x01(\x05\x12\r\n\x05\x65ssay\x18\x02 \x01(\x05\x12\x12\n\ntrue_false\x18\x03 \x01(\x05\"\xb2\x01\n\x18GenerateQuestionsRequest\x12!\n\x08lectures\x18\x01 \x03(\x0b\x32\x0f.LectureContent\x12\x17\n\x0ftotal_questions\x18\x02 \x01(\x05\x12\x32\n\x14\x64ifficulty_breakdown\x18\x03 \x01(\x0b\x32\x14.DifficultyBreakdown\x12&\n\x0etype_breakdown\x18\x04 \x01(\x0b\x32\x0e.TypeBreakdown\"j\n\x19GenerateQuestionsResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x15\n\rerror_message\x18\x02 \x01(\t\x12%\n\tquestions\x18\x03 \x03(\x0b\x32\x12.GeneratedQuestion\"\xba\x01\n\x11GeneratedQuestion\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x12\n\ndifficulty\x18\x03 \x01(\t\x12\r\n\x05topic\x18\x04 \x01(\t\x12\x13\n\x0b\x65xplanation\x18\x05 \x01(\t\x12!\n\x07options\x18\x06 \x03(\x0b\x32\x10.GeneratedOption\x12\x14\n\x0cmodel_answer\x18\x07 \x01(\t\x12\x18\n\x10grading_criteria\x18\x08 \x03(\t\"3\n\x0fGeneratedOption\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x12\n\nis_correct\x18\x02 \x01(\x08\x32\x93\x01\n\rExamAIService\x12;\n\x0cIndexLecture\x12\x14.IndexLectureRequest\x1a\x15.IndexLectureResponse\x12\x45\n\x0cGenerateExam\x12\x19.GenerateQuestionsRequest\x1a\x1a.GenerateQuestionsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.examgen_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INDEXLECTUREREQUEST']._serialized_start=24
  _globals['_INDEXLECTUREREQUEST']._serialized_end=118
  _globals['_INDEXLECTURERESPONSE']._serialized_start=120
  _globals['_INDEXLECTURERESPONSE']._serialized_end=206
  _globals['_LECTURECONTENT']._serialized_start=208
  _globals['_LECTURECONTENT']._serialized_end=286
  _globals['_DIFFICULTYBREAKDOWN']._serialized_start=288
  _globals['_DIFFICULTYBREAKDOWN']._serialized_end=353
  _globals['_TYPEBREAKDOWN']._serialized_start=355
  _globals['_TYPEBREAKDOWN']._serialized_end=418
  _globals['_GENERATEQUESTIONSREQUEST']._serialized_start=421
  _globals['_GENERATEQUESTIONSREQUEST']._serialized_end=599
  _globals['_GENERATEQUESTIONSRESPONSE']._serialized_start=601
  _globals['_GENERATEQUESTIONSRESPONSE']._serialized_end=707
  _globals['_GENERATEDQUESTION']._serialized_start=710
  _globals['_GENERATEDQUESTION']._serialized_end=896
  _globals['_GENERATEDOPTION']._serialized_start=898
  _globals['_GENERATEDOPTION']._serialized_end=949
  _globals['_EXAMAISERVICE']._serialized_start=952
  _globals['_EXAMAISERVICE']._serialized_end=1099
# @@protoc_insertion_point(module_scope)
