syntax = "proto3";

service ExamAIService{
    rpc IndexLecture (IndexLectureRequest) returns (IndexLectureResponse);
    rpc GenerateExam (GenerateQuestionsRequest) returns (GenerateQuestionsResponse);
   rpc GradeAnswer (GradeAnswerRequest) returns (GradeAnswerResponse);
    // rpc GradeImageAnswer (GradeImageAnswerRequest) returns (GradeAnswerResponse);
    // rpc ExplainConcept (ExplainConceptRequest) returns (ExplainConceptResponse);
    rpc pre_summary (GenerateSummaryRequest) returns (GenerateSummaryResponse)
}
    
    message GenerateSummaryRequest{
        string course_id=1;
        repeated WeakTopic weak_topics=2;
    }
    message WeakTopic{
        string topic=1;
        string lecture_id =2;
        int32 missed_count =3;
        int32 total_attempted=4;
    }
    
message TopicReview {
    string topic = 1;
    string lecture_id =2;
    string focus_points = 3;   
}

message GenerateSummaryResponse {
    bool success = 1;
    string error_message = 2;
    repeated TopicReview reviews = 3;
}
    message IndexLectureRequest{
        string lecture_id =1;
        string course_id =2;
        string user_id =3;
        string content=4;
    }

    message IndexLectureResponse{
        bool success =1;
        string error_message = 2;
        int32 chunks_indexed=3 ;
    }

    message LectureContent {
        string lecture_id = 1;
        int32 questions_count = 3;
    }

    message DifficultyBreakdown {
       int32 easy = 1;
       int32 medium = 2;
       int32 hard = 3;
    }

    message TypeBreakdown {
      int32 mcq = 1;
      int32 essay = 2;
      int32 true_false = 3;
    }

    message GenerateQuestionsRequest {
      repeated LectureContent lectures = 1;
      int32 total_questions = 2;
      DifficultyBreakdown difficulty_breakdown = 3;
      TypeBreakdown type_breakdown = 4;
   }
   message GenerateQuestionsResponse {
       bool success = 1;
      string error_message = 2;
      repeated GeneratedQuestion questions = 3;
    }
    message GeneratedQuestion {
       string text = 1;
       string type = 2;              
       string difficulty = 3;        
       string topic = 4;
       string explanation = 5;
       repeated GeneratedOption options = 6; 
       string model_answer = 7;               
       repeated string grading_criteria = 8;   
       string lecture_id =9;
    }

    message GeneratedOption {
      string text = 1;
      bool is_correct = 2;
    }
    message GradeAnswerRequest {
        string lecture_id=1;
        string student_answer=2;
        string question_text=3;
        int32 max_score=4;
        string model_answer=5;
        string grading_criteria=6;
    }
    message GradeAnswerResponse {
        bool success=1;
        string error_message=2;
        double score =3;
        string feedback=4;
       repeated string missing_point =5;
        string confidence=6;
    }
